-- Create proposals table for the admin proposal builder.
create table if not exists public.proposals (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by uuid default auth.uid(),
  proposal_number bigint generated by default as identity unique not null,
  proposal_reference text unique not null,
  issue_date date default current_date not null,
  language text not null default 'POR' check (language in ('ENG', 'POR', 'ITA')),
  valid_until text,
  client_name text not null default '',
  client_organization text,
  event_name text,
  event_date text,
  event_location text,
  guest_attendance text,
  menu_format text,
  concept_statement text,
  presenter_name text,
  presenter_title text,
  items jsonb not null default '[]'::jsonb
);

create or replace function public.set_proposal_reference()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.proposal_reference is null or btrim(new.proposal_reference) = '' then
    new.proposal_reference :=
      'SV-' ||
      extract(year from coalesce(new.issue_date, current_date))::int::text ||
      '-' ||
      lpad(new.proposal_number::text, 3, '0');
  end if;

  return new;
end;
$$;

drop trigger if exists set_proposal_reference_on_insert on public.proposals;
create trigger set_proposal_reference_on_insert
  before insert on public.proposals
  for each row
  execute function public.set_proposal_reference();

create or replace function public.set_proposals_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists set_proposals_updated_at_on_update on public.proposals;
create trigger set_proposals_updated_at_on_update
  before update on public.proposals
  for each row
  execute function public.set_proposals_updated_at();

alter table public.proposals enable row level security;

create policy "Only authenticated users can view proposals" on public.proposals
  for select using (auth.role() = 'authenticated');

create policy "Only authenticated users can create proposals" on public.proposals
  for insert with check (auth.role() = 'authenticated');

create policy "Only authenticated users can update proposals" on public.proposals
  for update using (auth.role() = 'authenticated');

create policy "Only authenticated users can delete proposals" on public.proposals
  for delete using (auth.role() = 'authenticated');
